// Generates seed/seed.sql — deterministic fake catalogue, customers and
// ~3.5 months of raw usage events. Re-run with `npm run seed:generate`.
//
// Deterministic (seeded PRNG) so that tests and demos are reproducible.

import { writeFileSync, mkdirSync } from "node:fs";

// ── Tiny seeded PRNG (mulberry32) ────────────────────────────────────
function rng(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = rng(20260916);
const jitter = (base, pct) => Math.round(base * (1 + (rand() * 2 - 1) * pct));

// ── Catalogue ────────────────────────────────────────────────────────
const plans = [
  { id: "free", name: "Free", base_fee_cents: 0 },
  { id: "pro", name: "Pro", base_fee_cents: 2000 },
  { id: "business", name: "Business", base_fee_cents: 20000 }
];

const skus = [
  {
    id: "workers_requests",
    name: "Workers requests",
    unit: "requests",
    unit_size: 1_000_000,
    aggregation: "sum"
  },
  {
    id: "workers_cpu_ms",
    name: "Workers CPU time",
    unit: "CPU-ms",
    unit_size: 1_000_000,
    aggregation: "sum"
  },
  {
    id: "r2_storage_gb_month",
    name: "R2 storage",
    unit: "GB-month",
    unit_size: 1,
    aggregation: "avg_daily"
  },
  {
    id: "r2_class_a_ops",
    name: "R2 Class A operations",
    unit: "operations",
    unit_size: 1_000_000,
    aggregation: "sum"
  },
  {
    id: "ai_neurons",
    name: "Workers AI neurons",
    unit: "neurons",
    unit_size: 1_000,
    aggregation: "sum"
  }
];

// included_qty in raw units; unit_price_cents per sku.unit_size above that.
const planPrices = {
  free: {
    workers_requests: [3_000_000, 0], // hard cap in reality; we bill 0 for the demo
    workers_cpu_ms: [300_000, 0],
    r2_storage_gb_month: [10, 0],
    r2_class_a_ops: [1_000_000, 0],
    ai_neurons: [10_000, 0]
  },
  pro: {
    workers_requests: [10_000_000, 30], // $0.30 / million
    workers_cpu_ms: [30_000_000, 2], // $0.02 / million CPU-ms
    r2_storage_gb_month: [10, 2], // $0.02 / GB-month (1.5 cents rounded up)
    r2_class_a_ops: [1_000_000, 450], // $4.50 / million
    ai_neurons: [10_000, 1] // $0.011 / 1k neurons -> 1 cent
  },
  business: {
    workers_requests: [50_000_000, 30],
    workers_cpu_ms: [150_000_000, 2],
    r2_storage_gb_month: [50, 2],
    r2_class_a_ops: [5_000_000, 450],
    ai_neurons: [100_000, 1]
  }
};

// Customers with distinct usage "personalities" (daily base volumes).
const customers = [
  {
    id: "cus_acme",
    name: "Acme Static Sites",
    plan_id: "pro",
    created_at: "2025-11-03T09:12:00Z",
    daily: {
      workers_requests: 700_000,
      workers_cpu_ms: 1_800_000,
      r2_storage_gb_month: 0,
      r2_class_a_ops: 40_000,
      ai_neurons: 0
    },
    r2_gb: 14 // steady storage footprint
  },
  {
    id: "cus_pixelforge",
    name: "PixelForge AI",
    plan_id: "pro",
    created_at: "2026-02-18T14:40:00Z",
    daily: {
      workers_requests: 250_000,
      workers_cpu_ms: 4_000_000,
      r2_storage_gb_month: 0,
      r2_class_a_ops: 120_000,
      ai_neurons: 9_000
    },
    r2_gb: 38,
    growth: 0.018 // AI usage growing ~1.8%/day -> overage in recent months
  },
  {
    id: "cus_northwind",
    name: "Northwind Logistics",
    plan_id: "business",
    created_at: "2025-06-30T08:00:00Z",
    daily: {
      workers_requests: 2_400_000,
      workers_cpu_ms: 9_000_000,
      r2_storage_gb_month: 0,
      r2_class_a_ops: 300_000,
      ai_neurons: 1_500
    },
    r2_gb: 120,
    spikeDays: ["2026-08-11", "2026-08-12"] // incident: 6x traffic
  },
  {
    id: "cus_hobby",
    name: "Dana's Blog",
    plan_id: "free",
    created_at: "2026-05-05T19:22:00Z",
    daily: {
      workers_requests: 40_000,
      workers_cpu_ms: 90_000,
      r2_storage_gb_month: 0,
      r2_class_a_ops: 500,
      ai_neurons: 0
    },
    r2_gb: 2
  }
];

// ── Event generation ─────────────────────────────────────────────────
const START = new Date("2026-06-01T00:00:00Z");
const END = new Date("2026-09-16T00:00:00Z"); // exclusive; "today" in the demo
const SAMPLES_PER_DAY = 4; // metering pipeline flushes every 6h

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const lines = [];
lines.push("-- GENERATED by scripts/generate-seed.mjs — do not edit by hand.");
lines.push(
  "DELETE FROM invoice_lines; DELETE FROM invoices; DELETE FROM usage_events;"
);
lines.push(
  "DELETE FROM customers; DELETE FROM plan_prices; DELETE FROM skus; DELETE FROM plans;"
);

for (const p of plans)
  lines.push(
    `INSERT INTO plans VALUES (${q(p.id)}, ${q(p.name)}, ${p.base_fee_cents});`
  );
for (const s of skus)
  lines.push(
    `INSERT INTO skus VALUES (${q(s.id)}, ${q(s.name)}, ${q(s.unit)}, ${s.unit_size}, ${q(s.aggregation)});`
  );
for (const [plan, prices] of Object.entries(planPrices))
  for (const [sku, [inc, price]] of Object.entries(prices))
    lines.push(
      `INSERT INTO plan_prices VALUES (${q(plan)}, ${q(sku)}, ${inc}, ${price});`
    );
for (const c of customers)
  lines.push(
    `INSERT INTO customers VALUES (${q(c.id)}, ${q(c.name)}, ${q(c.plan_id)}, 'USD', ${q(c.created_at)});`
  );

let eventCount = 0;
const eventRows = [];
for (const c of customers) {
  let dayIndex = 0;
  for (
    let d = new Date(START);
    d < END;
    d.setUTCDate(d.getUTCDate() + 1), dayIndex++
  ) {
    const dayStr = d.toISOString().slice(0, 10);
    const dow = d.getUTCDay();
    const weekend = dow === 0 || dow === 6 ? 0.55 : 1;
    const growth = c.growth ? Math.pow(1 + c.growth, dayIndex) : 1;
    const spike = c.spikeDays?.includes(dayStr) ? 6 : 1;

    for (const sku of skus) {
      if (sku.id === "r2_storage_gb_month") {
        // Storage is sampled once a day as GB stored; the rating engine
        // turns daily GB samples into GB-months (avg over the month).
        const gb = jitter(
          c.r2_gb * (c.growth ? Math.pow(1.004, dayIndex) : 1),
          0.02
        );
        eventRows.push([
          `${c.id}:${sku.id}:${dayStr}`,
          c.id,
          sku.id,
          gb,
          `${dayStr}T23:59:00Z`,
          "r2-metering"
        ]);
        continue;
      }
      const base = c.daily[sku.id];
      if (!base) continue;
      const aiGrowth = sku.id === "ai_neurons" ? growth : 1;
      const dayTotal = base * weekend * spike * aiGrowth;
      for (let s = 0; s < SAMPLES_PER_DAY; s++) {
        const qty = Math.max(0, jitter(dayTotal / SAMPLES_PER_DAY, 0.25));
        const hh = String(s * 6).padStart(2, "0");
        eventRows.push([
          `${c.id}:${sku.id}:${dayStr}:${s}`,
          c.id,
          sku.id,
          qty,
          `${dayStr}T${hh}:00:00Z`,
          sku.id.startsWith("r2")
            ? "r2-metering"
            : sku.id === "ai_neurons"
              ? "ai-gateway"
              : "workers-metering"
        ]);
      }
    }
  }
}

// Batch inserts (D1 handles multi-row VALUES fine; keep batches modest).
const BATCH = 200;
for (let i = 0; i < eventRows.length; i += BATCH) {
  const chunk = eventRows.slice(i, i + BATCH);
  const values = chunk
    .map(
      ([k, cu, sk, qty, at, src]) =>
        `(${q(k)}, ${q(cu)}, ${q(sk)}, ${qty}, ${q(at)}, ${q(src)})`
    )
    .join(",\n  ");
  lines.push(
    `INSERT INTO usage_events (idempotency_key, customer_id, sku_id, quantity, occurred_at, source) VALUES\n  ${values};`
  );
  eventCount += chunk.length;
}

mkdirSync("seed", { recursive: true });
writeFileSync("seed/seed.sql", lines.join("\n") + "\n");
console.log(
  `seed/seed.sql written: ${customers.length} customers, ${eventCount} usage events`
);
